name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_manager: [pip, pipenv, poetry]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
      - name: Run Dagger Pipelines
        run: dagger run deno run -A ../../src/dagger/runner.ts
        working-directory: example/${{ matrix.package_manager }}
        env:
          PACKAGE_MANAGER: ${{ matrix.package_manager }}
