name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_manager: [pip, pipenv, poetry]
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.37
      - name: Setup Fluent CI CLI
        run: deno install -A -r https://cli.fluentci.io -n fluentci
      - name: Setup Dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.8.8 sh
          sudo mv bin/dagger /usr/local/bin
          dagger version
      - name: Run Dagger Pipelines
        run: |
          rm ../../deno.lock
          dagger run deno run -A ../../src/dagger/runner.ts
        working-directory: example/${{ matrix.package_manager }}
        env:
          PACKAGE_MANAGER: ${{ matrix.package_manager }}
